"""
Trains one Ridge Regression model per variant (baseline/lifestyle/conservative)
on synthetic data generated by generate_synthetic_data.py, and saves all three
into a single pickle bundle.

Because the synthetic data is generated directly from the existing linear
formula, Ridge with a very small alpha will recover it almost exactly --
this is intentional. Once real confirmed_actual_spending data exists, swap
the data source in this script (see NOTE below) and re-tune alpha properly
via cross-validation, same as before.

Usage:
    python models/train.py
"""
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split

NUMERIC_FEATURES = [
    "monthly_allowance",
    "distance_from_campus",
    "outings_per_month",
    "gaming_hours",
    "club_events",
    "mobile_data_usage",
    "year_of_study",
    "printing_frequency",
]

CATEGORICAL_FEATURES = {
    "accommodation_type": ["hostel", "pg", "rented", "home"],  # hostel = baseline
    "transport_type": ["walk", "bicycle", "public", "own_vehicle"],  # walk = baseline
    "meal_habits": ["mess", "home", "cafe", "mixed"],  # mess = baseline
}

TARGET_COLUMN = "predicted_spending"  # NOTE: swap to "confirmed_actual_spending"
                                       # once real labeled data exists.

LABELS = {
    "monthly_allowance": "Monthly allowance",
    "distance_from_campus": "Distance from campus",
    "outings_per_month": "Outings",
    "gaming_hours": "Gaming hours",
    "club_events": "Club events",
    "mobile_data_usage": "Mobile data",
    "year_of_study": "Year of study",
    "printing_frequency": "Printing",
}


def build_feature_matrix(df: pd.DataFrame):
    """One-hot encode categoricals (dropping the baseline category, matching
    the TS convention where e.g. hostel/walk/mess contribute 0), and return
    the full ordered list of column names alongside the numpy matrix."""
    parts = [df[NUMERIC_FEATURES]]
    encoded_columns = list(NUMERIC_FEATURES)

    for col, categories in CATEGORICAL_FEATURES.items():
        baseline, *others = categories
        for cat in others:
            colname = f"{col}__{cat}"
            parts.append((df[col] == cat).astype(int).rename(colname))
            encoded_columns.append(colname)

    X = pd.concat(parts, axis=1).values
    return X, encoded_columns


def train_variant(variant: str, alpha: float = 0.01):
    df = pd.read_csv(f"data/synthetic_{variant}.csv")
    X, feature_columns = build_feature_matrix(df)
    y = df[TARGET_COLUMN].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    model = Ridge(alpha=alpha)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    print(f"[{variant}] R²={r2:.4f}  MAE={mae:.2f}  (rows={len(df)})")

    return {
        "model": model,
        "feature_columns": feature_columns,
        "intercept": float(model.intercept_),
    }


def main():
    bundle = {}
    for variant in ["baseline", "lifestyle", "conservative"]:
        bundle[variant] = train_variant(variant)

    Path("models").mkdir(exist_ok=True)
    with open("models/spending_models.pkl", "wb") as f:
        pickle.dump(bundle, f)
    print("\nSaved all 3 variant models to models/spending_models.pkl")


if __name__ == "__main__":
    main()
